# Generated by Django 2.1 on 2018-11-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('trener', models.BooleanField()),
                ('aktivni', models.BooleanField(default=0)),
                ('imgur_id', models.CharField(blank=True, max_length=100)),
                ('nad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letadlo.Osoba')),
            ],
        ),
    ]
