# Generated by Django 2.1 on 2018-11-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letadlo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='nad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='letadlo.Osoba'),
        ),
    ]
