# Generated by Django 2.1 on 2018-10-01 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pullup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misto',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='misto',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misto',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='misto',
            name='uploaded_to_mapbox',
            field=models.BooleanField(default=False),
        ),
    ]
