# Generated by Django 2.1 on 2018-10-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pullup', '0002_auto_20181001_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Potrebuje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povinny', models.BooleanField(default=False)),
                ('cvik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullup.Cvik')),
            ],
        ),
        migrations.CreateModel(
            name='Telo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Varianta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(blank=True, max_length=500)),
                ('obtiznost', models.SmallIntegerField(default=0)),
                ('cvik1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvik1', to='pullup.Cvik')),
                ('cvik2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvik2', to='pullup.Cvik')),
            ],
        ),
        migrations.CreateModel(
            name='Vybaveni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='potrebuje',
            name='vybaveni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullup.Vybaveni'),
        ),
        migrations.AddField(
            model_name='cvik',
            name='telo',
            field=models.ManyToManyField(to='pullup.Telo'),
        ),
        migrations.AddField(
            model_name='cvik',
            name='varianty',
            field=models.ManyToManyField(through='pullup.Varianta', to='pullup.Cvik'),
        ),
        migrations.AddField(
            model_name='cvik',
            name='vybaveni',
            field=models.ManyToManyField(through='pullup.Potrebuje', to='pullup.Vybaveni'),
        ),
        migrations.AddField(
            model_name='misto',
            name='vybaveni',
            field=models.ManyToManyField(to='pullup.Vybaveni'),
        ),
        migrations.AlterUniqueTogether(
            name='varianta',
            unique_together={('cvik1', 'cvik2')},
        ),
    ]
