# Generated by Django 2.1 on 2018-10-13 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pullup', '0003_auto_20181012_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='nazev',
            field=models.CharField(default='nazev', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='popis',
            field=models.CharField(default='popis', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telo',
            name='latin',
            field=models.CharField(default='latin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvik',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='misto',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telo',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vybaveni',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
