# Generated by Django 2.1 on 2018-10-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullup', '0006_auto_20181018_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvik',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='misto',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='telo',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vybaveni',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
    ]
