# Generated by Django 2.1 on 2018-10-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullup', '0013_auto_20181020_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvik',
            options={'verbose_name_plural': 'Cviky'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Média', 'verbose_name_plural': 'Média'},
        ),
        migrations.AlterModelOptions(
            name='misto',
            options={'verbose_name': 'Místo', 'verbose_name_plural': 'Místa'},
        ),
        migrations.AlterModelOptions(
            name='potrebuje',
            options={'verbose_name': 'Potřeba', 'verbose_name_plural': 'Potřeby'},
        ),
        migrations.AlterModelOptions(
            name='pouzitimedia',
            options={'verbose_name': 'Použití média', 'verbose_name_plural': 'Použití médií'},
        ),
        migrations.AlterModelOptions(
            name='telo',
            options={'verbose_name': 'Část těla', 'verbose_name_plural': 'Části těl'},
        ),
        migrations.AlterModelOptions(
            name='typmedia',
            options={'verbose_name': 'Typ média', 'verbose_name_plural': 'Typy médií'},
        ),
        migrations.AlterModelOptions(
            name='varianta',
            options={'verbose_name_plural': 'Varianty'},
        ),
        migrations.AlterModelOptions(
            name='vybaveni',
            options={'verbose_name': 'Vybavení', 'verbose_name_plural': 'Vybavení'},
        ),
        migrations.AddField(
            model_name='typmedia',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
